--INSERT INTO SAMPLE VALUES('1', 'VALUE1');
--INSERT INTO SAMPLE VALUES('2', 'VALUE2');


INSERT INTO DEVICE VALUES(1, 5, 'Windows', 'Antivirus');
INSERT INTO DEVICE VALUES(2, 7, 'Mac', 'Antivirus');
INSERT INTO DEVICE VALUES(3, 3, 'NA', 'Backup');
INSERT INTO DEVICE VALUES(4, 2, 'NA', 'PSA');
INSERT INTO DEVICE VALUES(5, 1, 'NA', 'Screen Share');