--INSERT DEVICES
INSERT INTO DEVICE VALUES(1, 5, 'Windows', 'Antivirus');
INSERT INTO DEVICE VALUES(2, 7, 'Mac', 'Antivirus');
INSERT INTO DEVICE VALUES(3, 3, 'NA', 'Backup');
INSERT INTO DEVICE VALUES(4, 2, 'NA', 'PSA');
INSERT INTO DEVICE VALUES(5, 1, 'NA', 'Screen Share');


CREATE TABLE IF NOT EXISTS ORDERS (
    ID         INT NOT NULL AUTO_INCREMENT,
    DEVICE_ITEMS VARCHAR(50) NOT NULL,
    DEVICES    INT NOT NULL
);

--INSERT ORDERS
INSERT INTO ORDERS(ID, DEVICE_ITEMS, DEVICES) VALUES(1, '1-2,2-3,3-5,5-5', 5);
